### ISSUE TITLE
Add Flow support

### ISSUE THREAD

**Issue by montogeek** [trevordmiller/nova-atom-syntax#18]
Hi!

Slick theme and syntax, great work!

I would like to request [Flow](https://flowtype.org/) support, this is how it looks on Atom:
![screen shot 2016-09-26 at 09 59 16](https://cloud.githubusercontent.com/assets/1002461/18839314/2395c4e6-83d0-11e6-9fd2-c25cb119b317.png)

This is how it looks with [Oceanic next](https://github.com/voronianski/oceanic-next-color-scheme)
![screen shot 2016-09-26 at 10 02 10](https://cloud.githubusercontent.com/assets/1002461/18839358/4e862dc6-83d0-11e6-9eca-ae473b85dd26.png)

Thanks!

**Comment by trevordmiller** [comment]
@montogeek Thanks for using Nova and for your feedback! I would like to add this as well. Feel free to submit a PR using [the "CONTRIBUTING" guidelines on the Nova website](https://trevordmiller.github.io/nova); otherwise, I'll get to it at some point :)

**Comment by trevordmiller** [comment]
If anyone wants to open this and take care of it feel free. I'm closing for now as I have other priorities. Sorry.
