### ISSUE TITLE
No cursor blinking?

### ISSUE THREAD

**Issue by Tuccinator** [trevordmiller/nova-atom-syntax#21]
I'm not too sure if this is an issue or something default. My cursor doesn't seem to be blinking.

**Comment by trevordmiller** [comment]
Thanks for the feedback! Seems like the theme is incorrectly overriding blinking cursor styles. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)

**Comment by Tuccinator** [comment]
I have been looking around for a fix but have been unable to find one. I would be glad if you were able to do it :) thanks!

**Comment by trevordmiller** [comment]
If anyone wants to open this and take care of it feel free. I'm closing for now as I have other priorities. Sorry.
