### ISSUE TITLE
tsx

### ISSUE THREAD

**Issue by braxtonchristensen** [trevordmiller/nova-atom-syntax#31]
is there support for tsx? if no would you want a PR?

**Comment by trevordmiller** [comment]
@braxtonchristensen Thank you for using Nova! I haven't used the .tsx file extension, but as long as the typescript Atom plugin maps the typescript syntax groups to the native syntax groups the highlighting should work as expected. Do you mind trying it out and letting me know if it looks right?

**Comment by braxtonchristensen** [comment]
just got an update today from the atom typescript plugin things still seem to be a little bit off. here are a couple examples can get a better/ more complete example for you if it would help.
<img width="605" alt="screen shot 2017-06-26 at 11 13 33 am" src="https://user-images.githubusercontent.com/11494223/27551510-f179ea88-5a60-11e7-93ee-3fcc69e4e280.png">
<img width="468" alt="screen shot 2017-06-26 at 11 15 49 am" src="https://user-images.githubusercontent.com/11494223/27551515-f6182f8c-5a60-11e7-8896-6d17eb20d362.png">

**Comment by trevordmiller** [comment]
Oh yeah that is definitely off - mist have custom class names. Feel free to submit a pull request using the `CONTRIBUTING.md` file. Otherwise, I'll get to this at some point :)

**Comment by braxtonchristensen** [comment]
@trevordmiller hey man I submitted a pull request while on the train this morning, let me know if it looks okay or if you need me to change something.

**Comment by trevordmiller** [comment]
@braxtonchristensen Hey Braxton, I was literally just commenting on it haha. It looks great, thank you! I'll get it merged in and released soon :) Thanks for using Nova and for your pull request 💪

**Comment by trevordmiller** [comment]
Closed by https://github.com/trevordmiller/nova-atom-syntax/pull/32
