### ISSUE TITLE
Cursor in insert vs. command mode (vim-mode)

### ISSUE THREAD

**Issue by keithjgrant** [trevordmiller/nova-atom-syntax#7]
Gorgeous theme. Thanks for making it :)

I use the vim-mode plugin (https://atom.io/packages/vim-mode). Typically, the cursor is used to distinguish when I am in insert mode (thin cursor "|") vs command mode (block cursor, highlighting current character "∎").

With the nova syntax theme enabled, I see a block cursor in both modes. I need some way to visually distinguish between the two modes.

**Comment by trevordmiller** [comment]
@keithjgrant Thanks for using Nova! As long as the `vim-mode` package provides a different class for the two cursor types, that shouldn't be a problem to update. If you want to submit a pull request, feel free! Otherwise, I'll take care of it no problem. Thanks again.

**Comment by keithjgrant** [comment]
I’m swamped w/ conference prep & some writing deadlines at the moment. If you get to it first, cool. If not, I might be able to give it a go in a couple weeks.

**Comment by trevordmiller** [comment]
@keithjgrant No problem. I'll probably knock it out sometime in the next few days :)

**Comment by trevordmiller** [comment]
@keithjgrant It was a super easy 1-liner fix - I just needed to let Atom use its default variable and not override it. If you update to latest (`nova-atom-syntax` `1.2.2`) your cursor should change between vim modes :)

**Comment by keithjgrant** [comment]
Awesome. Thanks!
